#Database
POSTGRESQL_USERNAME: user
POSTGRESQL_PASSWORD: letmein
POSTGRESQL_HOST: localhost
POSTGRESQL_PORT: 5432
POSTGRESQL_DATABASE: userDatabase

#Server
CONTAINER_PORT: 8085
ACTIVE_PROFILE: dev

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: dwadson3@gmail.com
EMAIL_PASSWORD: cpkd ychj jtgs lqdd
VERIFY_EMAIL_HOST: http://localhost:5173

JWT_EXPIRATION: 432_000_000
#JWT_SECRET: ${SECRET}

JWT_SECRET: uDJTsAMm2XHFV3Ib4YeapsRZF2v+bRrICDtkH4sBbRuGYxq49vmy6I4ZG3GLMc+FlgDgQsdLdJdhojq0Vouirg==